#!/usr/bin/env bash

set -e

notmuch search --output=files --exclude=false "tag:deleted and not path:deleted/**" | while read item; do
    mv $item ~/.mail/deleted/
done

( cd ~/.mail/account.gmail/
  gmi sync)

offlineimap
