#!/usr/bin/env bash

set -e

move ()
{
    d1=$(basename $1 | cut -c1-2)
    d2=$(basename $1 | cut -c3-4)
    mkdir -p $2/$d1/$d2/
    mv $1 $2/$d1/$d2/
}

notmuch search --output=files --exclude=false "tag:deleted and not path:deleted/**" | while read item; do
    move $item ~/.mail/deleted/ || true
done

notmuch search --output=files "tag:archive" | while read item; do
    move $item ~/.mail/archive/ || true
done
notmuch tag -archive -- tag:archive

notmuch search --output=files "path:account.gmail/**" | while read item; do
    move $item ~/.mail/archive/ || true
done


( cd ~/.mail/account.gmail/
  gmi sync)

offlineimap
