#!/usr/bin/env bash

set -e

notmuch search --output=files --exclude=false "tag:deleted and not path:deleted/**" | while read item; do
    mv $item ~/.mail/deleted/ || true
done

notmuch search --output=files "tag:archive" | while read item; do
    mv $item ~/.mail/archive/ || true
done
notmuch tag -archive -- tag:archive


( cd ~/.mail/account.gmail/
  gmi sync)

offlineimap
