(evil-mode)

(setq
 evil-emacs-state-modes '(Custom-mode
                          Electric-buffer-menu-mode
                          archive-mode
                          bbdb-mode
                          biblio-selection-mode
                          bookmark-bmenu-mode
                          bookmark-edit-annotation-mode
                          browse-kill-ring-mode
                          bzr-annotate-mode
                          calc-mode
                          cfw:calendar-mode
                          completion-list-mode
                          custom-theme-choose-mode
                          debugger-mode
                          delicious-search-mode
                          desktop-menu-blist-mode
                          desktop-menu-mode
                          doc-view-mode
                          dvc-bookmarks-mode
                          dvc-diff-mode
                          dvc-info-buffer-mode
                          dvc-log-buffer-mode
                          dvc-revlist-mode
                          dvc-revlog-mode
                          dvc-status-mode
                          dvc-tips-mode
                          ediff-meta-mode
                          ediff-mode
                          efs-mode
                          elfeed-search-mode
                          elfeed-show-mode
                          emms-browser-mode
                          emms-mark-mode
                          emms-metaplaylist-mode
                          emms-playlist-mode
                          ess-help-mode
                          etags-select-mode
			  eww-mode
                          fj-mode
                          gc-issues-mode
                          gdb-breakpoints-mode
                          gdb-disassembly-mode
                          gdb-frames-mode
                          gdb-locals-mode
                          gdb-memory-mode
                          gdb-registers-mode
                          gdb-threads-mode
                          gist-list-mode
                          git-rebase-mode
                          gnus-article-mode
                          gnus-browse-mode
                          gnus-group-mode
                          gnus-server-mode
                          gnus-summary-mode
                          google-maps-static-mode
			  haskell-error-mode
			  haskell-interactive-mode
                          ibuffer-mode
                          jde-javadoc-checker-report-mode
                          magit-branch-manager-mode
                          magit-cherry-mode
                          magit-commit-mode
                          magit-diff-mode
                          magit-key-mode
                          magit-log-mode
                          magit-log-select-mode
                          magit-mode
                          magit-popup-mode
                          magit-popup-sequence-mode
                          magit-process-mode
                          magit-rebase-mode
                          magit-reflog-mode
                          magit-refs-mode
                          magit-revision-mode
                          magit-stash-mode
                          magit-stashes-mode
                          magit-status-mode
                          magit-wazzup-mode
                          mh-folder-mode
                          monky-mode
                          mpuz-mode
                          mu4e-headers-mode
                          mu4e-main-mode
                          mu4e-view-mode
                          notmuch-hello-mode
                          notmuch-message-mode
                          notmuch-search-mode
                          notmuch-show-mode
                          notmuch-tree-mode
                          occur-mode
                          org-agenda-mode
                          package-menu-mode
                          pdf-outline-buffer-mode
                          pdf-view-mode
                          proced-mode
                          rcirc-mode
                          rebase-mode
                          recentf-dialog-mode
                          reftex-select-bib-mode
                          reftex-select-label-mode
                          reftex-toc-mode
                          sldb-mode
                          slime-inspector-mode
                          slime-thread-control-mode
                          slime-xref-mode
                          sr-buttons-mode
                          sr-mode
                          sr-tree-mode
                          sr-virtual-mode
                          tar-mode
                          tetris-mode
                          tla-annotate-mode
                          tla-archive-list-mode
                          tla-bconfig-mode
                          tla-bookmarks-mode
                          tla-branch-list-mode
                          tla-browse-mode
                          tla-category-list-mode
                          tla-changelog-mode
                          tla-follow-symlinks-mode
                          tla-inventory-file-mode
                          tla-inventory-mode
                          tla-lint-mode
                          tla-logs-mode
                          tla-revision-list-mode
                          tla-revlog-mode
                          tla-tree-lint-mode
                          tla-version-list-mode
                          twittering-mode
                          urlview-mode
                          vc-annotate-mode
                          vc-dir-mode
                          vc-git-log-view-mode
                          vc-hg-log-view-mode
                          vc-svn-log-view-mode
                          vm-mode
                          vm-summary-mode
                          w3m-mode
                          wab-compilation-mode
                          xgit-annotate-mode
                          xgit-changelog-mode
                          xgit-diff-mode
                          xgit-revlog-mode
                          xhg-annotate-mode
                          xhg-log-mode
                          xhg-mode
                          xhg-mq-mode
                          xhg-mq-sub-mode
                          xhg-status-extra-mode)

 evil-motion-state-modes '(Buffer-menu-mode
                           Info-mode
                           Man-mode
                           apropos-mode
                           calendar-mode
                           color-theme-mode
                           command-history-mode
                           compilation-mode
                           dictionary-mode
                           elfeed-show-mode
                           ert-results-mode
                           help-mode
                           speedbar-mode
                           undo-tree-visualizer-mode
                           woman-mode))
